version: 2

updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - "thomaslaurenson"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - "dependencies"
    groups:
      dev-dependencies:
        dependency-type: "development"
    assignees:
      - "thomaslaurenson"
