# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: smount

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    binary: >-
      smount-{{ .Os }}-{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}
    no_unique_dist_dir: true
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/thomaslaurenson/smount/cmd.Version={{.Version}}

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

git:
  ignore_tags:
    - "*-dev"
    - "dev"
