name: Lint

on: workflow_call

permissions:
  contents: read

jobs:
  go_lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - run: make fmt_check

      - run: make mod_check

      - run: make vet
