name: PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/**"
      - "**.go"
      - go.mod
      - go.sum
      - .goreleaser*.yml
      - .gpipe.yml
      - Makefile

permissions:
  contents: read

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
